config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
	resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					  length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end	


	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
		#render plain: params[:article].inspect	
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :text
    = f.text_area :text

  %p
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

= link_to 'New article', new_article_path

%table
  %tr
    %th
      Title
    %th
      Text

  - @articles.each do |article|
    %tr
      %td= article.title
      %td= article.text
      %td= link_to 'Show', article_path(article)
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article_path(article),
        method: :delete,
        data: { confirm: 'Are you sure?' }

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
  %strong
    Title:
  = @article.title

%p
  %strong
    Text:
  = @article.text

%h2 Comments
= render @article.comments

%h2 Add a comment:
= render 'comments/form'

= link_to 'Back', articles_path
|
= link_to 'Edit', edit_article_path(@article)

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter

%p
  %strong Comment:
  = comment.body

%p
  = link_to 'Destroy Comment', [comment.article, comment],
            method: :delete,
            data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
= form_for ([@article, @article.comments.build]) do |f|
  %p
    = f.label :commenter
    %br
    = f.text_field :commenter
  %p
    = f.label :body
    %br
    = f.text_area :body
  %p
    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
%h1 Hello, Rails!

= link_to 'My Blog', controller: 'articles'